services:
  app:
    build:
      context: .
      target: dev
    container_name: carro-ideal-app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: carro_ideal
    command: air

  db:
    image: postgres:15
    container_name: carro-ideal-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carro_ideal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command: >
      -path=/migrations
      -database=postgres://postgres:postgres@db:5432/carro_ideal?sslmode=disable
      up

volumes:
  postgres_data: